### ISSUE TITLE
Error when using authenticated request to get detailed report 

### ISSUE THREAD

**Issue by rheinardkorf** [wptide/tide-issues#10]
Fetching a detailed report such as https://wptide.local/api/tide/v1/report/1234/raw/phpcs_phpcompatibility produces an error despite being an authenticated request and resource being available in bucket.

```
{
    "code": "report_fetch_error",
    "message": "Fetching report failed",
    "data": {
        "status": 500
    }
}
```

**Comment by valendesigns** [comment]
I can confirm that I'm seeing the same response even though authenticated.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535489232000100) today, we're keeping this in the `1.0.0` release.  This is only happening in production, locally it's all working.  @valendesigns to finish fixing the build process then redeploy and test.

**Comment by jeffpaul** [comment]
Issue moved to [wptide/wptide #151](https://github.com/wptide/wptide/issues/151) via [**ZenHub**](https://www.zenhub.com/)
