### ISSUE TITLE
Integrate with `wp-deprecated-code-scanner`

### ISSUE THREAD

**Issue by rheinardkorf** [wptide/tide-issues#2]
The project at https://github.com/JDGrimes/wp-deprecated-code-scanner "scans for all deprecated functions in a codebase".  

This will be handy as an audit to determine the usage of deprecated functions.

Thanks @jdrimes for pointing it out.

**Comment by JDGrimes** [comment]
Just to be clear, (because I know it is confusing,) this scans for deprecated functions *declared* in the code, not usages of deprecated functions.

It is used to build the list of deprecated WordPress functions for WPCS's deprecated functions sniff though.

**Comment by jeffpaul** [comment]
Per [bugscrub](https://wordpress.slack.com/archives/C7TK8FBUJ/p1535488612000100) today, we're moving this to `Future Release`.

**Comment by jeffpaul** [comment]
Issue moved to [wptide/wptide #153](https://github.com/wptide/wptide/issues/153) via [**ZenHub**](https://www.zenhub.com/)
